### ISSUE TITLE
License needs to be changed to continue to be listed at Redis Modules

### ISSUE THREAD

**Issue by brennanfee** [RedisLabsModules/countminsketch#9]
This has got to be fixed in order to actually be open source. The Redis modules site explicitly states, "Only modules under an OSI approved license are listed here." Commons Clause IS NOT OSI APPROVED.

**Comment by itamarhaber** [comment]
Hello @brennanfee 

Please take a minute of your time to read this repository's license - AFAIK AGPL is OSI approved.

Closing this issue.

**Comment by brennanfee** [comment]
My bad, you are correct.  Thanks!
